### PR TITLE
Add: kube-router cni configuration

### PR DESCRIPTION
**Pull request by methodx**
Hi

When I try to deploy kubernetes v1.12.0 or v1.12.1 I noticed that kube-router doesn't start at all. If I'm getting it right, we need to create cni configuration file - it should work.

Thanks

### CODE REVIEW

**Comment by murali-reddy** [comment]
> When I try to deploy kubernetes v1.12.0 or v1.12.1 I noticed that kube-router doesn't start at all.

@methodx please see https://github.com/cloudnativelabs/kube-router/issues/547

is it because of toleration?

**Comment by methodx** [comment]
@murali-reddy that's it, thank you!
Added that **bold** option, everything works.

Also, FYI, I added one more thing:
```
- name: kube-router | Delete kube-proxy pods
  shell: "rm -rf /etc/kubernetes/manifests/kube-proxy.manifest"
  when: kube_router_run_service_proxy
```

**Comment by jjo** [comment]
> @murali-reddy that's it, thank you!
> Added that **bold** option, everything works.
> 
> Also, FYI, I added one more thing:
> 
> ```
> - name: kube-router | Delete kube-proxy pods
>   shell: "rm -rf /etc/kubernetes/manifests/kube-proxy.manifest"
>   when: kube_router_run_service_proxy
> ```

Note that this should be already handled by added `kube_proxy_remove`
(set_fact), it's a bit more complex as it needs to also cope with `kubeadm_enabled: true`
(which doesn't create kube-proxy manifests at node).
Voiding to write that manifest is specifically handled at https://github.com/jjo/kubespray/blob/jjo-add-kube-router-support/roles/kubernetes/node/tasks/main.yml#L145, wonder
if this isn't working for you ?

**Comment by methodx** [comment]
@jjo it works.
I rechecked task main for node. Don't know why, but it looks like I used old version of set_fact for kube_proxy.

**Pull request closed without merging**
